version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout
      # ... steps for building/testing app ...

#      - setup_remote_docker:
#          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -f packages/theseus/Dockerfile -t tikal/candidator_fuze19_daniel_group:$TAG .
#          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#          docker push tikal/candidator_fuze19_daniel_group:$TAG
