version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: fuzeteam3/candidator
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -f packages/theseus/Dockerfile -t $IMAGE_NAME:$CIRCLE_BUILD_NUM .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $IMAGE_NAME:latest

      # ... steps for building/testing app ...

#      - setup_remote_docker:
#          docker_layer_caching: true

      # build and push Docker image
#      - run: |
#          TAG=0.1.$CIRCLE_BUILD_NUM
#          docker build -f packages/theseus/Dockerfile -t tikal/candidator_fuze19_daniel_group:$TAG .
#          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#          docker push tikal/candidator_fuze19_daniel_group:$TAG
#      - name: docker
#        args: