version: 2.1
jobs:
  build:
    working_directory: packages/theseus
    environment:
      IMAGE_NAME: fuzeteam3/candidator
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -f Dockerfile -t $IMAGE_NAME:$CIRCLE_BUILD_NUM .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $IMAGE_NAME:$CIRCLE_BUILD_NUM $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $IMAGE_NAME:latest
